import type { Genre, Mood, MoodId, Track } from "@/types/moodify";

export const moods: Mood[] = [
  { id: "vibing", name: "Vibing", emoji: "😎", description: "Good energy, zero agenda.", color: "#f6bd60", shade: "#69421c", ink: "#2b1b0b" },
  { id: "sad", name: "Sad", emoji: "😔", description: "Feel it all. Stay a while.", color: "#9eb8f4", shade: "#243a71", ink: "#121d3d" },
  { id: "romantic", name: "Romantic", emoji: "❤️", description: "A little heart on your sleeve.", color: "#f7a5bc", shade: "#793047", ink: "#471b2a" },
  { id: "energetic", name: "Energetic", emoji: "🔥", description: "Turn the whole day up.", color: "#ff986c", shade: "#903b29", ink: "#4b1d13" },
  { id: "calm", name: "Calm", emoji: "🧘", description: "Take the scenic route inward.", color: "#a6d5bd", shade: "#30644e", ink: "#183c2d" },
  { id: "focused", name: "Focused", emoji: "🧠", description: "Find your flow state.", color: "#aeb4fc", shade: "#42459b", ink: "#27295f" },
  { id: "melancholic", name: "Melancholic", emoji: "🌧️", description: "Beautifully bittersweet.", color: "#bac4d3", shade: "#495467", ink: "#293140" },
  { id: "party", name: "Party", emoji: "🎉", description: "Main room, main character.", color: "#ddb0ff", shade: "#703d96", ink: "#45215f" },
  { id: "road-trip", name: "Road Trip", emoji: "🚗", description: "The journey is the point.", color: "#f4cf8d", shade: "#9c613a", ink: "#56331f" },
  { id: "late-night", name: "Late Night", emoji: "🌙", description: "For the hours that are yours.", color: "#a0b8d6", shade: "#334c72", ink: "#172940" },
];

export const genres: Genre[] = ["Any", "Pop", "Hip-Hop", "Rock", "Electronic", "R&B", "Indie", "Bollywood", "Lo-fi"];

export const moodById = Object.fromEntries(moods.map((mood) => [mood.id, mood])) as Record<MoodId, Mood>;

// Curated discovery data. Apple Music search links are used in unconnected mode.
const rows: Array<[string, string, string, Exclude<Genre, "Any">, number, MoodId[], number]> = [
  ["Blinding Lights", "The Weeknd", "After Hours", "Pop", 85, ["vibing", "energetic", "late-night", "road-trip"], 200],
  ["After Dark", "Mr.Kitty", "Time", "Electronic", 56, ["late-night", "melancholic", "vibing"], 258],
  ["Nightcall", "Kavinsky", "OutRun", "Electronic", 64, ["late-night", "road-trip", "melancholic"], 258],
  ["The Less I Know The Better", "Tame Impala", "Currents", "Indie", 70, ["vibing", "late-night", "road-trip"], 216],
  ["Electric Feel", "MGMT", "Oracular Spectacular", "Indie", 76, ["vibing", "party", "road-trip"], 229],
  ["Sunflower", "Post Malone & Swae Lee", "Spider-Man: Into the Spider-Verse", "Hip-Hop", 66, ["vibing", "calm", "road-trip"], 158],
  ["Pink + White", "Frank Ocean", "Blonde", "R&B", 42, ["calm", "romantic", "late-night"], 184],
  ["Nights", "Frank Ocean", "Blonde", "R&B", 60, ["late-night", "vibing", "melancholic"], 307],
  ["Good Days", "SZA", "SOS", "R&B", 45, ["calm", "sad", "romantic"], 279],
  ["Snooze", "SZA", "SOS", "R&B", 48, ["romantic", "calm", "late-night"], 201],
  ["Die For You", "The Weeknd", "Starboy", "R&B", 62, ["romantic", "late-night", "sad"], 260],
  ["Adore You", "Harry Styles", "Fine Line", "Pop", 68, ["romantic", "vibing", "road-trip"], 207],
  ["golden hour", "JVKE", "this is what ____ feels like", "Pop", 55, ["romantic", "calm", "road-trip"], 209],
  ["Until I Found You", "Stephen Sanchez", "Easy On My Eyes", "Pop", 40, ["romantic", "melancholic", "calm"], 177],
  ["Ocean Eyes", "Billie Eilish", "dont smile at me", "Pop", 36, ["sad", "calm", "melancholic"], 200],
  ["when the party's over", "Billie Eilish", "WHEN WE ALL FALL ASLEEP", "Pop", 27, ["sad", "melancholic", "late-night"], 196],
  ["everything i wanted", "Billie Eilish", "everything i wanted", "Pop", 38, ["sad", "melancholic", "late-night"], 245],
  ["Someone You Loved", "Lewis Capaldi", "Divinely Uninspired", "Pop", 42, ["sad", "melancholic"], 182],
  ["Another Love", "Tom Odell", "Long Way Down", "Indie", 55, ["sad", "melancholic", "romantic"], 244],
  ["The Night We Met", "Lord Huron", "Strange Trails", "Indie", 39, ["sad", "melancholic", "late-night"], 208],
  ["Space Song", "Beach House", "Depression Cherry", "Indie", 41, ["melancholic", "late-night", "calm"], 321],
  ["Fade Into You", "Mazzy Star", "So Tonight That I Might See", "Indie", 36, ["melancholic", "romantic", "late-night"], 295],
  ["505", "Arctic Monkeys", "Favourite Worst Nightmare", "Rock", 63, ["melancholic", "late-night", "road-trip"], 253],
  ["Do I Wanna Know?", "Arctic Monkeys", "AM", "Rock", 59, ["late-night", "romantic", "road-trip"], 272],
  ["Sweater Weather", "The Neighbourhood", "I Love You.", "Indie", 60, ["late-night", "romantic", "vibing"], 240],
  ["Apocalypse", "Cigarettes After Sex", "Cigarettes After Sex", "Indie", 33, ["late-night", "melancholic", "romantic"], 290],
  ["Nothing's Gonna Hurt You Baby", "Cigarettes After Sex", "I.", "Indie", 26, ["romantic", "calm", "late-night"], 286],
  ["Holocene", "Bon Iver", "Bon Iver", "Indie", 31, ["calm", "melancholic", "focused"], 336],
  ["re: Stacks", "Bon Iver", "For Emma, Forever Ago", "Indie", 22, ["calm", "sad", "focused"], 401],
  ["Bloom", "The Paper Kites", "Woodland", "Indie", 28, ["calm", "romantic", "focused"], 211],
  ["Sunset Lover", "Petit Biscuit", "Presence", "Electronic", 48, ["calm", "focused", "road-trip"], 237],
  ["A Walk", "Tycho", "Dive", "Electronic", 40, ["focused", "calm", "road-trip"], 316],
  ["Awake", "Tycho", "Awake", "Electronic", 50, ["focused", "calm", "vibing"], 283],
  ["Intro", "The xx", "xx", "Electronic", 38, ["focused", "late-night", "calm"], 127],
  ["Weightless", "Marconi Union", "Weightless", "Electronic", 18, ["calm", "focused"], 489],
  ["Experience", "Ludovico Einaudi", "In a Time Lapse", "Electronic", 40, ["focused", "calm", "melancholic"], 315],
  ["Snowman", "WYS", "Snowman", "Lo-fi", 25, ["focused", "calm", "late-night"], 142],
  ["affection", "Jinsang", "life.", "Lo-fi", 22, ["focused", "calm", "melancholic"], 108],
  ["Coffee Breath", "Sofia Mills", "Coffee Breath", "Lo-fi", 28, ["focused", "calm", "romantic"], 160],
  ["Dreaming", "Kupla", "Kingdom in Blue", "Lo-fi", 30, ["focused", "calm", "late-night"], 171],
  ["Monday Loop", "Tomppabeats", "Harbor", "Lo-fi", 32, ["focused", "calm", "vibing"], 137],
  ["Luv(sic) Part 3", "Nujabes", "Modal Soul", "Hip-Hop", 42, ["focused", "calm", "vibing"], 339],
  ["Feather", "Nujabes", "Modal Soul", "Hip-Hop", 54, ["focused", "vibing", "calm"], 175],
  ["HUMBLE.", "Kendrick Lamar", "DAMN.", "Hip-Hop", 91, ["energetic", "party"], 177],
  ["DNA.", "Kendrick Lamar", "DAMN.", "Hip-Hop", 94, ["energetic", "party"], 185],
  ["SICKO MODE", "Travis Scott", "ASTROWORLD", "Hip-Hop", 92, ["party", "energetic"], 312],
  ["goosebumps", "Travis Scott", "Birds in the Trap Sing McKnight", "Hip-Hop", 79, ["party", "late-night", "vibing"], 244],
  ["Nonstop", "Drake", "Scorpion", "Hip-Hop", 87, ["energetic", "party"], 238],
  ["Levitating", "Dua Lipa", "Future Nostalgia", "Pop", 86, ["party", "energetic", "vibing"], 203],
  ["Don't Start Now", "Dua Lipa", "Future Nostalgia", "Pop", 85, ["party", "energetic", "vibing"], 183],
  ["As It Was", "Harry Styles", "Harry's House", "Pop", 74, ["vibing", "road-trip", "party"], 167],
  ["Shut Up and Dance", "WALK THE MOON", "TALKING IS HARD", "Rock", 92, ["party", "road-trip", "energetic"], 199],
  ["Mr. Brightside", "The Killers", "Hot Fuss", "Rock", 88, ["party", "road-trip", "energetic"], 222],
  ["Dog Days Are Over", "Florence + The Machine", "Lungs", "Indie", 88, ["energetic", "road-trip", "party"], 252],
  ["Midnight City", "M83", "Hurry Up, We're Dreaming", "Electronic", 77, ["late-night", "road-trip", "party"], 243],
  ["A Moment Apart", "ODESZA", "A Moment Apart", "Electronic", 68, ["road-trip", "vibing", "calm"], 235],
  ["Strobe", "deadmau5", "For Lack of a Better Name", "Electronic", 77, ["focused", "late-night", "energetic"], 637],
  ["Titanium", "David Guetta & Sia", "Nothing but the Beat", "Electronic", 95, ["energetic", "party"], 245],
  ["Wake Me Up", "Avicii", "True", "Electronic", 87, ["road-trip", "energetic", "party"], 247],
  ["Levels", "Avicii", "Levels", "Electronic", 96, ["party", "energetic"], 199],
  ["Believer", "Imagine Dragons", "Evolve", "Rock", 92, ["energetic", "road-trip"], 204],
  ["Eye of the Tiger", "Survivor", "Eye of the Tiger", "Rock", 94, ["energetic", "road-trip"], 246],
  ["Take Me Out", "Franz Ferdinand", "Franz Ferdinand", "Rock", 84, ["party", "road-trip", "vibing"], 237],
  ["Ilahi", "Arijit Singh", "Yeh Jawaani Hai Deewani", "Bollywood", 76, ["road-trip", "vibing"], 228],
  ["Safarnama", "Lucky Ali", "Tamasha", "Bollywood", 56, ["road-trip", "calm", "melancholic"], 251],
  ["Kabira", "Tochi Raina & Rekha Bhardwaj", "Yeh Jawaani Hai Deewani", "Bollywood", 49, ["romantic", "melancholic", "road-trip"], 223],
  ["Agar Tum Saath Ho", "Alka Yagnik & Arijit Singh", "Tamasha", "Bollywood", 38, ["sad", "romantic", "melancholic"], 341],
  ["Tum Hi Ho", "Arijit Singh", "Aashiqui 2", "Bollywood", 45, ["romantic", "sad"], 262],
  ["Kesariya", "Arijit Singh", "Brahmāstra", "Bollywood", 64, ["romantic", "vibing"], 268],
  ["Ghungroo", "Arijit Singh & Shilpa Rao", "War", "Bollywood", 88, ["party", "vibing", "energetic"], 302],
  ["Kala Chashma", "Amar Arshi, Badshah & Neha Kakkar", "Baar Baar Dekho", "Bollywood", 94, ["party", "energetic"], 187],
  ["Apna Bana Le", "Arijit Singh", "Bhediya", "Bollywood", 55, ["romantic", "calm"], 261],
  ["Chaleya", "Arijit Singh & Shilpa Rao", "Jawan", "Bollywood", 72, ["romantic", "vibing"], 200],
];

const artColors = ["#e8928c", "#b8a7d9", "#78a9a0", "#dfb06e", "#6680b3", "#ba806f", "#8ba6aa", "#c7a4a1", "#8d91bc", "#baae77"];

export const tracks: Track[] = rows.map(([title, artist, album, genre, energy, trackMoods, duration], index) => ({
  id: `track-${index + 1}`,
  title,
  artist,
  album,
  genre,
  energy,
  moods: trackMoods,
  duration,
  color: artColors[index % artColors.length],
}));
